- name: Restore context for {{ opkssh_cmd }}
  ansible.builtin.command:
    cmd: "restorecon {{ opkssh_cmd }}"

- name: Setup SELinux module for opkssh (standard version)
  block:
    - name: Copy the SELinux type enforcement file (standard version)
      ansible.builtin.copy:
        src: "{{ role_dir }}/files/opkssh.te"
        dest: "/tmp/opkssh.te"
    - name: Compile the SELinux type enforcement file (standard version)
      ansible.builtin.command:
        cmd: "checkmodule -M -m -o /tmp/opkssh.mod /tmp/opkssh.te"
    - name: Compile the SELinux policy module (standard version)
      ansible.builtin.command:
        cmd: "semodule_package -o /tmp/opkssh.pp -m /tmp/opkssh.mod"
    - name: Load the SELinux policy module (standard version)
      ansible.builtin.command:
        cmd: "semodule -i /tmp/opkssh.pp"
    - name: Remove unneeded files
      ansible.builtin.file:
        path: "/tmp/opkssh.*"
        state: absent
  when: 
    - not opkssh_disable_home_policy
  
- name: Setup SELinux module for opkssh (no home version)
  block:
    - name: Copy the SELinux type enforcement file (no home version)
      ansible.builtin.copy:
        src: "{{ role_dir }}/files/opkssh-no-home.te"
        dest: "/tmp/opkssh.te"
    - name: Compile the SELinux type enforcement file (no home version)
      ansible.builtin.command:
        cmd: "checkmodule -M -m -o /tmp/opkssh-no-home.mod /tmp/opkssh-no-home.te"
    - name: Compile the SELinux policy module (no home version)
      ansible.builtin.command:
        cmd: "semodule_package -o /tmp/opkssh-no-home.pp -m /tmp/opkssh-no-home.mod"
    - name: Load the SELinux policy module (no home version)
      ansible.builtin.command:
        cmd: "semodule -i /tmp/opkssh-no-home.pp"
    - name: Remove unneeded files
      ansible.builtin.file:
        path: "/tmp/opkssh-no-home.*"
        state: absent
  when:
    - opkssh_disable_home_policy